name: Cheat request
description: Ask for a new cheat to be added to the cheat file.
title: "[Cheat Request]: Summarize the cheat you want"
labels: ["cheat"]
body:
  - type: textarea
    id: cheat
    attributes:
      label: Cheat info
      description: Write what cheat you want here.
      placeholder: Write what cheat you want here. Press "Submit issue" below when done.
    validations:
      required: true
